### ISSUE TITLE
Cleanup or2papers.py

### ISSUE THREAD

**Issue by tnaumann** [rycolab/aclpub2#102]
A few things top of mind:

- [x] Use argparse rather than attempting to read directly from `sys.argv` for username and password
- [x] Throw error rather than assume ACL 2022 for connection string
- [x] Wrap primary execution path in `main` function

**Comment by crux82** [comment]
@rswilkens can you please take a look at these suggestions? 

TNX

**Comment by zhzhang** [comment]
I'll go ahead and make these changes.

**Comment by rswilkens** [comment]
Thanks @zhzhang
