### ISSUE TITLE
Missing pdfs or other info about the papers

### ISSUE THREAD

**Issue by MirunaClinciu** [rycolab/aclpub2#115]
Many times authors might not provide a camera ready paper and this can raise some issues, e.g. this error: "pdf_file": submission.content["pdf"].split("/")[-1], KeyError: 'pdf.
As I had to solve this quickly, please find attached the following,  it might be useful:

or2papers.py 

![image](https://user-images.githubusercontent.com/6933123/178233968-f53b109a-fcb9-4dd0-b5ce-0419e27961d6.png)

openreview.py  

![image](https://user-images.githubusercontent.com/6933123/178234198-be762b5b-202f-4678-a5a1-e8c66746c4fd.png)

**Comment by yufanghou** [comment]
Thank you @MirunaClinciu!
