### ISSUE TITLE
Proper handling of non-archival submissions

### ISSUE THREAD

**Issue by mjpost** [rycolab/aclpub2#117]
For both ACL and NAACL we have had mistaken submissions of papers that were supposed to be non-archival. I'm not familiar enough with the process to understand why this is happening, but I'm wondering if there is something we could do in aclpub2 to help reduce this? Can we add a `publish: True` flag in the JSON on each paper, with a default value of `False`, for example?

**Comment by ryancotterell** [comment]
I think this is a good idea. I'll get it up and ready for EMNLP 2022.

**Comment by danielhers** [comment]
Just to make sure - is this how we should indicate archival (vs. non-archival) papers?

**Comment by d-ataman** [comment]
hi is the feature active? what is the default value? i am setting publish: False for non-archival papers. thanks!

**Comment by ryancotterell** [comment]
@zhzhang did we have a fix for this yet?

**Comment by zhzhang** [comment]
Is the goal to exclude papers where `publish: False` from proceedings?

**Comment by ryancotterell** [comment]
Yes

**Comment by zhzhang** [comment]
Gotcha. So the schedule will be printed in full, but only archival papers to appear in proceedings.
There's no fix yet but I'll go ahead and add shortly, with the flag `archival: True` being default.

**Comment by ryancotterell** [comment]
Thanks!

**Comment by danielhers** [comment]
Wait, `archival`? I thought it's `publish`.

**Comment by zhzhang** [comment]
I think the meaning of `archival` is more specific than `publish` right? Let me know if the other makes more sense.
My reasoning is to have the naming of this flag be as specific as possible since we're using these yaml files as input in multiple places.

**Comment by danielhers** [comment]
Sure, it makes sense to me either way. We should just finalize this soon because I've already told people to use `publish`, and the EMNLP proceedings deadline is approaching.

**Comment by zhzhang** [comment]
@danielhers would you be able to ask people to switch to `archival` as the field name?
I will go ahead and implement + close this in the evening.
Thanks for the patience.

**Comment by zhzhang** [comment]
That's correct, and to amend by earlier comment based on the original issue post by Matt, the default value will be `False` so papers will not be archival by default.

**Comment by davidjurgens** [comment]
Just to check, will this get integrated soon before the deadline? The NLP+CSS workshop also has non-archival papers that need to appear in the program but not the proceedings so we're looking forward to this feature :)

**Comment by zhzhang** [comment]
PR to fix is above @ryancotterell please review and merge if acceptable.
