### ISSUE TITLE
field name typo

### ISSUE THREAD

**Issue by mjpost** [rycolab/aclpub2#118]
The DeepLo [papers.yml file](https://www.dropbox.com/s/j5lh9h94zebcat9/papers.yml?dl=0) has the field name "instituion" for each author. Raising an issue in case this was generated.

**Comment by mjpost** [comment]
(Also, [the abstracts were all `t`](https://github.com/acl-org/acl-anthology/issues/2058), not sure why)

**Comment by ryancotterell** [comment]
These were both human errors :-(

**Comment by mjpost** [comment]
The best kind!
