### ISSUE TITLE
papers.yaml file filled with wrong information

### ISSUE THREAD

**Issue by xinru1414** [rycolab/aclpub2#124]
I've noticed that the `first name` and the `last name` fields in the `papers.yaml` are sometimes filled, both, with author's email addresses instead of their first name and last name.  This will cause ingestion errors -- author's email address will be ingested as their first and last name.

This has happened multiple times with different conference venues. I'm wondering what's causing it, and if there's anything we can do about it? From the ingestion side, we can certainly catch such errors and communicate with conference organizers so that they can fix the issues and resubmmit their ingestion material.

**Comment by zhzhang** [comment]
This has to do with unsanitized data coming from OpenReview.net or softconf I believe. @marcopoli any insight on this?

**Comment by xinru1414** [comment]
Someone said that this is because some authors did not register on Open Review so the python script was copying their email as first and last names. See [here](https://github.com/acl-org/acl-anthology/issues/1897).

**Comment by zhzhang** [comment]
Hm, I can't think of a way to address this without forcing people to register if their co-authors submit a paper.
How much names are affected? Is it feasible to fix it manually this time around?
