### ISSUE TITLE
Failure to compile proceedings

### ISSUE THREAD

**Issue by isi1314** [rycolab/aclpub2#129]
Compiling the proceedings fails with the following error. I would appreciate any input, thanks!!
<img width="1237" alt="Screen Shot 2022-11-22 at 10 07 47 AM" src="https://user-images.githubusercontent.com/6072141/203349647-da71f253-a51a-4d93-ac0a-258679ea709b.png">

**Comment by zhzhang** [comment]
This looks like a problem cloning the repo. What steps did you take that lead to this error?

**Comment by isi1314** [comment]
> This looks like a problem cloning the repo. What steps did you take that lead to this error?

Any small change and push leads to this, either with the automatic aclpub2 run on Github, or with an any push from my machine. Also running `aclpub2/bin/generate . --proceedings --overwrite ` on my machine compiles the papers and then gets stuck.

**Comment by zhzhang** [comment]
@isi1314 were you able to resolve this issue locally? If not, do you still need a resolution?

**Comment by crux82** [comment]
I think it can be closed: as no feedback is provided we can assume the problem is solved.
