### ISSUE TITLE
Error when compiling proceedings

### ISSUE THREAD

**Issue by danielpreotiuc** [rycolab/aclpub2#130]
Hello,

We have an issue when compiling proceedings for our workshop.

Here is the log: https://github.com/emnlp-2022/NLLP/actions/runs/3548495672/jobs/5959766272

It seems the error is: https://github.com/emnlp-2022/NLLP/actions/runs/3548623835/jobs/5960041782

but I am not sure how to fix it. The logs mention the sponsor logos, so I tried removing them, but it still failed.

I appreciate any input you would have.

**Comment by zhzhang** [comment]
@ryancotterell could you give me access to the emnlp-2022 organization so that I can have a look at this?

**Comment by zhzhang** [comment]
@danielpreotiuc if you have admin access to the NLLP repo, you may try granting me permission to view the errors and pull the repos as well!

**Comment by danielpreotiuc** [comment]
Sorry for the delay, added both @ryancotterell and @zhzhang as maintainers on the repo

**Comment by zhzhang** [comment]
@danielpreotiuc , this change should fix your issue, https://github.com/rycolab/aclpub2/pull/131
Though there are some latex issues in some other parts of the input as well.
@ryancotterell , please review the PR and merge when you get the chance!

**Comment by danielpreotiuc** [comment]
Thank you. It would be great to have that merged soon, so we can finalize. I had checked all submissions with aclpubcheck, so am wondering what the issues left are.

**Comment by crux82** [comment]
Thank you @zhzhang the code works!

@danielpreotiuc: Jordan allowed to add invited speakers without institutions. Sorry for this (stupid) question: do you really want to add an invited speaker without mentioning her/his institution?
