### ISSUE TITLE
Hardcoded information about papers in softconf script

### ISSUE THREAD

**Issue by carolscarton** [rycolab/aclpub2#141]
Hi, 

There was some information hardcoded in lines in the script to extract information from SoftConf. Basically, there were hardcoded keys and information that I believe were added to extract "demonstrations", but are not ideal for main conference and others. 

I opened a pull request that should solve the issue.

Carol

**Comment by crux82** [comment]
@carolscarton if you confirm that the issue is solved, can you please close this issue?
