### ISSUE TITLE
Handling non-archival submissions & findings presentations @ Workshops.

### ISSUE THREAD

**Issue by zeeraktalat** [rycolab/aclpub2#150]
For workshops, there is the issue that sometimes presentations need to be included into the program but a paper should not be included in the proceedings. There are two particular cases for this:

- Unarchived papers
- Findings papers presented at the workshop

At this point, the YAML config & associated code does not allow for this. This could presumably be handled by allowing a flag "archival: [true|false]" under each paper, where only those that have the flag set to true have the papers included.

**Comment by ryancotterell** [comment]
I think there is such a flag already!

Zeerak Talat ***@***.***> schrieb am Mi. 19. Apr. 2023 um
02:29:

**Comment by zeeraktalat** [comment]
So there is!

**Comment by zeeraktalat** [comment]
Actually, will need to reopen this. This approach only handles where all information is already held (i.e., the unarchived paper is from the workshop, not findings). Right now the support is only in papers.yml and it should be extended to program.yml.

**Comment by ryancotterell** [comment]
I think you have to add it to papers.yml. The program doesn’t have all the
information all the time.

Zeerak Talat ***@***.***> schrieb am Mi. 19. Apr. 2023 um
03:49:

**Comment by zeeraktalat** [comment]
You do, but what I'm saying is that adding a flag in program would be helpful too. :)
