### ISSUE TITLE
Issue with running or2papers.py script

### ISSUE THREAD

**Issue by firojalam** [rycolab/aclpub2#161]
Hi I have been trying to the following command, but having the error below. Any suggestion what could be the reason? Note I tried to install openreview package using both from source and pip, none is solving the problem. 

python or2papers.py "user" "pass" "EMNLP/2023/Workshop"

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.openreview.net/notes?invitation=EMNLP%2F2023%2FWorkshop%2FPaper.%2A%2F-%2FDecision&limit=1000&sort=id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "or2papers.py", line 171, in <module>
    main(args.username, args.password, args.venue, args.all, args.pdfs)
  File "or2papers.py", line 50, in main
    client_acl, invitation=venue + "/Paper.*/-/Decision"
  File "/Users/firojalamqcri/Others/BLP/blp-workshop/openreview-py/openreview/tools.py", line 1000, in iterget_notes
    return efficient_iterget(client.get_notes, desc='Getting Notes', **params)
  File "/Users/firojalamqcri/Others/BLP/blp-workshop/openreview-py/openreview/tools.py", line 781, in __init__
    self.current_batch, total = self.get_function(**self.params)
  File "/Users/firojalamqcri/Others/BLP/blp-workshop/openreview-py/openreview/openreview.py", line 1059, in get_notes
    response = self.__handle_response(response)
  File "/Users/firojalamqcri/Others/BLP/blp-workshop/openreview-py/openreview/openreview.py", line 130, in __handle_response
    raise OpenReviewException(error)
openreview.openreview.OpenReviewException: {'name': 'ValidationError', 'message': 'invitation must be a prefix regex. If validation passes, any remaining regex characters will be escaped.', 'status': 400, 'details': {'path': '.invitation', 'reqId': '2023-11-07-2049567'}}
(b

**Comment by crux82** [comment]
@rswilkens if I'm not mistaken you can help with this bug, or can't you?

**Comment by firojalam** [comment]
Hi @crux82, thanks. 
@rswilkens, if you can help on this it would be great. Kind of stuck here.

**Comment by erip** [comment]
I'm not sure if this is related, but I am having trouble even getting a handle on the associated workshops' invitations:

```python
>>> client.get_group("EMNLP/2023/Workshop/NLP-OSS").invitation is None
True
```

**Comment by rswilkens** [comment]
Hi @firojalam, have you already tried or2program_committee.py?
For the or2papers.py, you have to provide the venue ID as it is on OpenReview. For example:
python or2papers.py "user" "pass" "EMNLP/2023/Workshop/NLP-OSS"

**Comment by erip** [comment]
I will say that it doesn't work for me. Same error as @firojalam reported.

**Comment by rswilkens** [comment]
@erip, did you manage to run the or2program_committee.py?

**Comment by erip** [comment]
Neither script works.

**Comment by rswilkens** [comment]
@erip and @firojalam, please try to replace (lines 45 - 53)
`    decision_by_forum = {
        d.forum: d
        for d in list(
            openreview.tools.iterget_notes(
                client_acl, invitation=venue + "/Paper.*/-/Decision"
            )
        )
        if "accept" in d.content["decision"].lower()
    }
`    
with 
`    decision_by_forum = {
        d.forum: d
        for d in list(
            openreview.tools.iterget_notes(
                client_acl, invitation=venue + "/Paper.*" # "/Paper.*/-/Decision"
            )
        )
        if "decision" in d.content and "accept" in d.content["decision"].lower()
    }`
in the or2papers.py

**Comment by firojalam** [comment]
Hi, 
I solved this using a different approach. Used api version2 and needed to modify the code in different places. 
Commented line 40-55, and used the following with some additional changes. 
submissions = client_acl.get_all_notes(content={'venueid': 'your vanue id'})

**Comment by erip** [comment]
The issue is that EMNLP Is running with the v2 API but this client assumes v1 API.

**Comment by mpurver** [comment]
I'm experiencing the same issue with both scripts when trying to run this for EACL 2024 (venue as EACL/2024/Conference).

**Comment by zhzhang** [comment]
@mpurver please pull down the branch in this pull request and give it a try: https://github.com/rycolab/aclpub2/pull/165
It incorporates the changes from @rswilkens comment above: https://github.com/rycolab/aclpub2/issues/161#issuecomment-1808244596

**Comment by crux82** [comment]
@mpurver if it works I will accept the pull request

@@zhzhang thank you!!!

**Comment by mpurver** [comment]
@zhzhang no luck so far - it connects fine but the submissions and decision_by_forum lists are both empty.

**Comment by crux82** [comment]
I fear that our users do not have visibility of the papers. In any case, we should add some meaningful message in these cases for the users.

**Comment by crux82** [comment]
@haroldrubio can you please help us?

**Comment by haroldrubio** [comment]
I've made some changes in the OR scripts in this PR, please take a look and let me know if you run into some issues
- #166

**Comment by crux82** [comment]
@haroldrubio Thank you very much for your support! I can download the papers.

@zhzhang I think we will merge https://github.com/rycolab/aclpub2/pull/166 into the main branch.

Unfortunately, or2program_committee.py does not download anything. Could this be a problem related to my publication chair account on OperReview?

@mpurver can you download the committee?

**Comment by crux82** [comment]
It should be solved

**Comment by MirunaClinciu** [comment]
I need to add something here: the structure in OpenReview can vary between conferences and workshops. For instance, in a Main Conference track, submissions might be further divided into categories like 'Main' and 'Findings'. However, on the ACL website, these tracks are represented as tabs, and the current or2papers.py script cannot handle this differentiation because it only uses the venueid. This will raise the same error.

For example, in the extracted data from the OpenReview library, you might see something like 'venueid':'aclweb.org/ACL/2024/ARR_Commitment' and 'venue': 'ACL 2024 Main'. This makes it difficult to map the tracks directly as they appear on the ACL website, such as 'ACL 2024 Main' under a specific tab like 'Main Conference' or 'Findings'. Therefore, the script needs to be adapted to handle these variations in structure.
