### ISSUE TITLE
title on the front matter

### ISSUE THREAD

**Issue by Shimorina** [rycolab/aclpub2#27]
Hello,

When I compile our [workshop proceedings](https://github.com/acl-2022/HumanEval), the title on the front page begins with the year.

![image](https://user-images.githubusercontent.com/9607332/156941566-f36142fe-f7d1-42d2-95d5-12f6787f68f2.png)

**Comment by crux82** [comment]
Hi Anastasia, 

thank you for your suggestion

@zhzhang To solve this issue, I think we can just replace from the line

https://github.com/rycolab/aclpub2/blob/main/aclpub2/templates/proceedings.tex#L51

the statement     
`{\bf\LARGE \VAR{conference.start_date.year} \VAR{conference.name}}`
with
`{\bf\LARGE \VAR{conference.name}}`

Is it correct?

Thank you all

Danilo
