### ISSUE TITLE
integration of previous instructions

### ISSUE THREAD

**Issue by Shimorina** [rycolab/aclpub2#29]
For workshop proceedings generation, are we still following the recommendations from previous years that were created for START? For example, for the title page it is [recommended](https://github.com/acl-org/ACLPUB/blob/master/docs/start.md#step-41-title-page-sections-subtab) to put the name of the conference on top (`ACL 2022`), title without "workshop of" and so on.

**Comment by zhzhang** [comment]
@crux82 what's the verdict on this?
We can change the `conference_details.yml` to `venue_details.yml` maybe, and have some field to handle rendering the conference name on top, with the workshop title underneath?

**Comment by crux82** [comment]
No, even the workshops of the previous ACL did not adopt this recommendation. 

https://aclanthology.org/2021.iwslt-1.0.pdf
https://aclanthology.org/2021.splurobonlp-1.0.pdf
https://aclanthology.org/2021.mwe-1.0.pdf
(I just randomly selected the proceedings of some random workshops from https://aclanthology.org/events/acl-2021/)

**Comment by Shimorina** [comment]
Well, we did it at EACL last year: https://aclanthology.org/2021.humeval-1.0.pdf :)

And there were some others (with different variations):
https://aclanthology.org/2021.hcinlp-1.0.pdf
https://aclanthology.org/2021.hackashop-1.0.pdf
https://aclanthology.org/2021.dravidianlangtech-1.0.pdf
https://aclanthology.org/2021.bea-1.0.pdf
etc...

So the point here is if we adopt the instructions, to ensure consistency at the template-level provided by aclpub2. If we don't adopt them, then the guide should be changed accordingly.

**Comment by crux82** [comment]
Hi, you are totally right.

In fact, we are preparing a specific guide with Elena Cabrio (one of the Workshop chairs - @ElenaCabrio ) and we will update the "old" guide to avoid such inconsistencies. 

Since you already "tested" aclpub2, would you be so kind to be the first to check this guide in the next few days, to avoid such inconsistencies?

Thank you again for your support and suggestions. 

Bests

Danilo
