### ISSUE TITLE
Problems with pax and proceedings with hundred of papers

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#35]
@zhzhang @ryancotterell  I think I found the issue about the ACL compile error. 

It was not a problem only tied to `save_size`, but also to `pool_size`.

Here is what I did on my mac. 
First I relaxed the umount of files I could open:

`ulimit -S -n 2048`

I searched for the place to add my parameters: 

`kpsewhich --all texmf.cnf`

It pointed to the two files

```
/usr/local/texlive/2016/texmf.cnf`
/usr/local/texlive/2016/texmf-dist/web2c/texmf.cnf
```

The first one needed to be modified. I just added a larger 

```
pool_size = 20000000
save_size = 800000
```
(maybe too large, but I was not sure about the limit) and it seems to work!

I think that know we should re-add  `\usepackage{pax}` to `aclpub2/templates/proceedings.tex` and invoke twice `pdflatex` from `aclpub2/generate.py`.

Unfortunately, I fear we cannot apply Ryan's suggestion to merge smaller parts of the proceedings, as the reference to one page is "absolute" and it will be lost

**Comment by ryancotterell** [comment]
Great! So is this working now?

**Comment by crux82** [comment]
@zhzhang @ryancotterell : maybe I have a viable solution.

We can build two exported versions of the papers:
1. The main (whole) proceedings with the concatenation of papers, without inner links (so disabling the pax library).
2. A second export for *each* watermarked paper: each paper should be read, watermarked (even with pages), and saved, preserving the original inner links. After all, these are the papers that will be used in the future and for which links are needed. 

As a side-effect, links will be consistent in the watermarked papers (with the actual procedure, internal hyperlink are out-of-sync). 

What do you think? @zhzhang is it simple for the actual software?
I am pretty sure that such a workaround is gonna work

**Comment by crux82** [comment]
@zhzhang: we must remember to also include in the watermarked paper a dedicated paper with only the frontmatter (to be included alone in aclanthology)

**Comment by crux82** [comment]
@zhzhang @ryancotterell I shared with you on slack the link to the first versions of the proceedings with all long papers. If you like that output, you can close this issue.
