### ISSUE TITLE
 Title format in camera-ready version of ACL2022

### ISSUE THREAD

**Issue by ShuoLiang-95** [rycolab/aclpub2#38]
Following the instruction, I protect some letters with curly braces when I fill the title box, but after submitting, I notice that the curly braces also show on the title of the openreview page. 

![image](https://user-images.githubusercontent.com/54581582/158556540-75f12f87-498c-40e0-918b-c178f11001bc.png)

The instruction says "These curly braces will not appear in the online conference program or in the proceedings. They will only appear in the BibTeX file ..."  So I wonder if it is ok that these curly braces also show in the openreview page.

**Comment by ryancotterell** [comment]
This is not an ACLPUB2 issue. You should redirect the question to the ARR EiCs who are in charge of OpenReivew. Or is there someone else that should be emailed @crux82?
