### ISSUE TITLE
Handling Author's name in uppercase

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#40]
When name/family names in the papers.yml are uppercase, this is propagated in the author's index. 

@zhzhang What about processing this info so that only the first letter is uppercase?

@rswilkens Is it correct to apply this processing during your export?

**Comment by rswilkens** [comment]
Name export extracts only the information as it is stored on OR. Until now,
no post-processing has been applied.

**Comment by crux82** [comment]
@rswilkens My idea is that your export should post-process each name/surname/middle-name **that is completely uppercase** changing the first letter of each token (separated by spaces) in uppercase the remaining in lowercase...

Then, we are still able to manually fix some names...

If we apply this pre-processing in aclpub2... we would not be able to recover...
