### ISSUE TITLE
problem when generating program commitee

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#42]
When the first author of the `entries` in a block misses the `institution` field, the entire block is not displayed (i.e., it is not reported in the latex file). 

@rswilkens : can you check with the responsible(s) of the program committee (I imagine the Program Chair) to check this missing information?

@zhzhang : anyway, I suggest that, when the institution is missing, the software should not display:
`John Doe, `
but 
`John Doe` (without the comma). 
There may be a rare case that some institutions are actually missing....

**Comment by rswilkens** [comment]
I'll check with the PCs, but this might be critical for the workshops. The
institution field is from peoples' profiles on OR. In sum, will it trigger
an error every time someone doesn't fill in this field?

**Comment by crux82** [comment]
No, I just suggest removing the comma. 
It is then the responsibility of the volume editors (i.e., the organizers of each workshop) to check this information and eventually integrate it by hand...
However, I suggest adding the Institution in OpenReview as a required input.

**Comment by crux82** [comment]
@zhzhang Unfortunately, when the institution of the first entry of a group is missing, the group is still not shown
