### ISSUE TITLE
missing python scripts for OpenReview export

### ISSUE THREAD

**Issue by Shimorina** [rycolab/aclpub2#53]
Your README mentions two python scripts for OpenReview exports: `or2papers.py` and `or2program_committee.py`. However, I couldn't find them in this repository.

Could you please indicate where they are?

**Comment by crux82** [comment]
@rswilkens can you add them when ready?

Thanks!

**Comment by zhzhang** [comment]
Closing, as Rodrigo has added these already https://github.com/rycolab/aclpub2/tree/main/openreview

**Comment by Shimorina** [comment]
Both scripts give this:
```
Traceback (most recent call last):
  File "or2program_committee.py", line 15, in <module>
    from util import *
ModuleNotFoundError: No module named 'util'
```

**Comment by crux82** [comment]
The problem should be solved. 

@Shimorina : can you kindly confirm it?

**Comment by Shimorina** [comment]
Thank you, it works now!

However, in both files this line
`acl_name = 'aclweb.org/ACL/2022/Conference' if len(sys.argv)>3 else sys.argv[3]`

should be replaced with, for example,
`acl_name = 'aclweb.org/ACL/2022/Conference' if len(sys.argv) > 4 else sys.argv[3]`

Otherwise, the scripts never take the fourth argument with the workshop name and default to the ACL conference, and nothing is extracted.

When replaced, the extraction works correctly :)

**Comment by rswilkens** [comment]
It should be solved now. 
I replaced ">" by "<=".

**Comment by crux82** [comment]
Thanks @rswilkens !

@Shimorina : does it work for you?

**Comment by Shimorina** [comment]
yes, it should be working. However, new updates are only in the `openreview` branch, not on `master` :)

**Comment by crux82** [comment]
Merged!
