### ISSUE TITLE
or2papers.py does not extract accepted papers only

### ISSUE THREAD

**Issue by Shimorina** [rycolab/aclpub2#58]
I feel a little bit boring, but I have another issue for you, sorry!

`or2papers.py` currently extracts all submitted papers with both 'accept' and 'reject' status. However, README says that it should extract only accepted papers.

**Comment by crux82** [comment]
You are not absolutely boring! We really appreciate beta testers :-)

We will fix it (hopefully tomorrow with @rswilkens )

Stay tuned!

**Comment by rswilkens** [comment]
filter added

**Comment by Shimorina** [comment]
Thank you!

Just one little final remark concerning README. In the Warnings section it is written:

> The workshops that accepts the ARR commitment should be aware that the or2program_committee.py script only extracts data of submitted/committed papers.

It was not very clear for me what means "submitted/committed papers".

Currently the script doesn't extract accepted papers committed via ARR. It would be worth including this info in the warnings.
