### ISSUE TITLE
Add scripts for downloading material from Softconf

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#62]
@valeriobasile @ElenaCabrio I think it would be very useful to add your scripts to export information from Softconf into the ACLPUB2 format. 

Then, I would kindly ask you to extend the guide ad done for exporting information from OpenReview. It would be really helpful for some workshop organizers that are using softconf ;-)

TNX!

**Comment by valeriobasile** [comment]
First version online, see pull request https://github.com/rycolab/aclpub2/pull/84
We can take it from there.
