### ISSUE TITLE
Adding slides and websites of tutorials

### ISSUE THREAD

**Issue by chokkan** [rycolab/aclpub2#64]
I (as a tutorial co-chair of ACL 2022) am wondering how we can associate tutorial slides from ACL Anthology. There are probably two ways to do this:

1. Collect tutorial slides from instructors and include them as an attachment. I found one instance in https://aclanthology.org/events/acl-2019/#p19-4

In order to realize this, I may need to specify a file in `papers.yml`:

```
  badges:
    - type: Presentation
      url: presentations/1.pdf
```

2. Add a link to the website of a tutorial and ask tutorial instructors to upload the slides in the website. I've never seen this instance on ACL Anthology. I guess that the corresponding `papers.yml` could include something like this:

```
  badges:
    - type: Web
      url: https://some-url-of-the-tutorial/
```

I think the option 2 would be convenient because tutorial instructors can update their slides in the last minute or evan after a presentation. So, my questions are,

+ Is it allowed to put `type: Web` in `badges`?
+ Can ACL Anthology show a URL with this badge?

**Comment by crux82** [comment]
I think that you just add your file to the `attachment` folder and use the `attachment` field. 
In the field `attribute` you should apply the local path to the file (e.g., `  - file: attachments/90_zip`) or a URL (e.g., `  - file: https://some-url-of-the-tutorial/`). 
Finally, the attribute `type` type can be set to `presentation`.

Here a possible example

```yaml
  attachments:
  - file: attachments/1.pdf
    type: presentation
```

@mjpost do you confirm it?

**Comment by crux82** [comment]
In any way, please refer to this section of our "guide"

https://github.com/rycolab/aclpub2#papersyml

**Comment by chokkan** [comment]
I read this guide before.

But I also noticed that `attachments` fields were probably replaced with `badges` in [sigdial](https://github.com/rycolab/aclpub2/blob/main/examples/sigdial/papers.yml) example. Which is correct?

I'm not sure what kind of strings are allowed in the `type` field. The documentation says,

```
- type: Dataset | Note | Poster | Presentation | Software | Attachment
```

but I can only see `relased_code` and `released_model_artifact` in the sigdial example. These lowercase fields are not mentioned in the documentation.

**Comment by mjpost** [comment]
This looks correct (what Daniel noted). `released_code` and `released_model_artifact` should not be used. We could add `code` as another option, however.

> I think that you just add your file to the `attachment` folder and use the `attachment` field. In the field `attribute` you should apply the local path to the file (e.g., ` - file: attachments/90_zip`) or a URL (e.g., ` - file: https://some-url-of-the-tutorial/`). Finally, the attribute `type` type can be set to `presentation`.
> 
> Here a possible example
> 
> ```yaml
>   attachments:
>   - file: attachments/1.pdf
>     type: presentation
> ```
> 
> @mjpost do you confirm it?

**Comment by crux82** [comment]
@mjpost @chokkan you are right, the example was incorrect. 

I updated it. 
Notice that according to the guide, the attribute `file` can be used to express a file in the submission, while `url` is a link to external resources that should be linked in the Anthology. 

Are the example and guide clear now for you?

**Comment by chokkan** [comment]
@crux82 Thank you for updating the example and documentation. They are clear to me.
