### ISSUE TITLE
Trailing / is important

### ISSUE THREAD

**Issue by matthiasgalle** [rycolab/aclpub2#65]
OK, maybe I am the only one, but I just spent quite some time figuring out that the last '/' is not part of the ID of the workshop/conference.

Eg, if you run the scripts with `aclweb.org/ACL/2022/Conference/` instead of `aclweb.org/ACL/2022/Conference` than the openreview-py API returns empty lists.

My proposal would be to add a .strip('/') inside the script.

**Comment by crux82** [comment]
@rswilkens can you please take a look?

TNX

**Comment by rswilkens** [comment]
.strip('/') added. Thanks!
