### ISSUE TITLE
Error during sigdial (Misplaced alignment tab character & )

### ISSUE THREAD

**Issue by bharathichezhiyan** [rycolab/aclpub2#66]
While running this command
./bin/generate examples/sigdial --proceedings --handbook

Misplaced alignment tab character &.
<recently read> &
l.275    Ruihong Huang, Texas A\\&
                                                        M University, United States\\

**Comment by crux82** [comment]
Did you change the input from the sigdial example? 

In this case, remember that input text should be escaped to be later compiled in latex

**Comment by bharathichezhiyan** [comment]
I did not change it. 
Anyway it worked when I use the below commands. Thanks a million.
./bin/generate examples/sigdial --proceedings --overwite.

**Comment by crux82** [comment]
Perfect
