### ISSUE TITLE
Book title too long for the watermark

### ISSUE THREAD

**Issue by ivulic** [rycolab/aclpub2#68]
What should we do if the book title is too long and cannot fit into a single line in the watermark?

On START this would be solved by customising the placement around the following line in proceedings.tex:

\put(105,16){\makebox(0,0){\emph{Proceedings of Deep Learning Inside Out (DeeLIO 2022):\\ The 3rd Workshop on Knowledge Extraction and Integration for Deep Learning Architectures}, pages 1 - 24}}

Thanks!

**Comment by crux82** [comment]
We could add to the `conference_details.yml` an additional optional field called something like `watermark_book_title` where this line break can be added. 

If it is set, it is used to watermark the papers. If not, the original `book_title` can be used. 

@zhzhang @ryancotterell : what do you think? It may sound like a workaround, but it is ... simple and hopefully effective.

**Comment by crux82** [comment]
@ivulic I just uploaded a new branch

 https://github.com/rycolab/aclpub2/tree/program-reintroduced_trim-watermarks

that will be soon merged into the main branch. 

You can now add to `conference_details.yml` the optional field called `watermark_book_title` where the name of the proceedings can be customized. You find an example also in the same branch in the sigdial example. 

Does it solve your issue?
