### ISSUE TITLE
sponsor logos in proceedings rendering overlapping

### ISSUE THREAD

**Issue by esalesky** [rycolab/aclpub2#75]
The sponsor logos for our workshop are currently rendered overlapping:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/4117932/164114536-e75df8ea-1e50-4364-a6d5-fd4f050cbbb7.png">
Are there any guidelines on image size or ways to add line breaks to prevent this? 
Thanks!

**Comment by crux82** [comment]
Because your initial jpg file is (really) hi-res. 
It is new to me but latex itself is not able to downscale it. 
If you shrink it a little bit, it should work.

**Comment by esalesky** [comment]
Reducing resolution keeps them from overlapping; I'll play with resizing to make them look more similar.

**Comment by crux82** [comment]
If you are familiar with latex you can quite easily modify this template

https://github.com/rycolab/aclpub2/blob/01083652eb645ffc0d1119e95414303f2f0b0450/aclpub2/templates/proceedings.tex#L77-L89

Where the number `4` indicates the number of images per row and `0.21\linewidth` is the width of each image

**Comment by esalesky** [comment]
Okay, I can do that. Thank you very much for the exact pointers!
