### ISSUE TITLE
Problem in the attachment fields when exporting papers.yml from OpenReview

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#78]
@rswilkens : The attachments entries list attachment paths like “attachments/50_zip”  contain the underscore. 
There is no such file named 50_zip. Instead, there is attachments/50.zip

Is it a problem with the export script?

TNX

**Comment by rswilkens** [comment]
in fact, it creates the write file (e.g. attachments/50.zip) but the path in the yml is wrong (e.g. attachments/50_zip). I fixed the code.
