### ISSUE TITLE
Symbol \_ in the mails within the paper.yml file

### ISSUE THREAD

**Issue by crux82** [rycolab/aclpub2#81]
@rswilkens in the actual export we have several e-mails with the symbol \_ in the e-mails in the papars.yml

Is it due to an incorrect escape?

**Comment by rswilkens** [comment]
That's odd. The last yml files I've shared contain "\_" instead of "_" in
the email fields, as requested (27/Mar). Can you send some examples by
Slack?

**Comment by crux82** [comment]
@rswilkens Sorry you are right. I was confused by the mail from Underline. 
My fault.

Closing
