### ISSUE TITLE
special characters in names

### ISSUE THREAD

**Issue by Shimorina** [rycolab/aclpub2#82]
in `papers.yml`, one author last name contains a special Vietnamese character: `Lưu`

So the proceedings don't compile with the following error:
```
! Package inputenc Error: Unicode character ư (U+01B0) (inputenc) not set up for use with LaTeX.
```
Can author names contain such characters, or should the name be modified? The ACL Anthology allows for diacritics in surnames (like `Müller`) but I'm not sure about `ư`.

Related to https://github.com/acl-org/aclpubcheck/issues/25

**Comment by crux82** [comment]
Aclpub2 generates LaTeX that shuold be compiled when in utf8. Can you try to replace with ư ?

**Comment by mjpost** [comment]
The Anthology supports any unicode character. The issue here is just with your LaTeX setup.

**Comment by Shimorina** [comment]
> Aclpub2 generates LaTeX that shuold be compiled when in utf8. Can you try to replace with ư ?

Sorry I didn't understand. Yes, I had tried to compile with `ư` but it gives the compilation error indicated above.

Following the [ACL template](https://www.overleaf.com/read/crtcwgxzjskr) for papers, this compilation problem can be solved if I add `\usepackage[T5]{fontenc}` to `proceedings.tex`.

**Comment by crux82** [comment]
great

**Comment by crux82** [comment]
We will check ASAP if `\usepackage[T5]{fontenc}` works well in general and replace in the official release

**Comment by crux82** [comment]
I commented on this issue in the Readme. 

The input templates use the T1 font encoding. If you are interested in different encodings (e.g., Vietnamese) you have to modify the `aclpub2/templates/proceedings.tex` by changing the statement `\usepackage[T1]{fontenc}` and specifying a different encoding, e.g., `\usepackage[T5]{fontenc}`.

It should solve the issue.

**Comment by MirunaClinciu** [comment]
I resolved the Unicode issues on Windows / Ubuntu Terminal by installing
apt-get install language-pack-ne language-pack-ne-base mythes-ne ttf-devanagari-fonts libreoffice-l10n-ne
