### ISSUE TITLE
Need page ranges in the metadata

### ISSUE THREAD

**Issue by mjpost** [rycolab/aclpub2#86]
BibTeX exports in the Anthology including page numbers as metadata ([for example](https://aclanthology.org/2021.acl-long.1.bib)). This is something of an anachronism but we should still support it. So we need this information as fields in `papers.yaml`.

**Comment by mjpost** [comment]
This is done automatically using pdfinfo in [the original script](https://github.com/acl-org/ACLPUB/blob/master/bin/manage-db.pl), by iterating through the papers.

**Comment by crux82** [comment]
@mjpost it is the same method used in aclpub2 to count page. Do you think this is enough or you prefer the page numbers made explicit?

**Comment by zhzhang** [comment]
We can insert this information into the output papers.yaml
