### ISSUE TITLE
program on multiple pages may overlap page #s, watermark

### ISSUE THREAD

**Issue by esalesky** [rycolab/aclpub2#89]
If a section in program.yml overflows onto a new page, such as listing multiple papers for a poster session which goes onto a 1-2  continued pages, the last entry per page will overlap with the page numbers as shown below:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/4117932/168316551-39759dd2-3aed-4c88-96ea-a594ba820f17.png">

**Comment by esalesky** [comment]
I have hacked this by changing `max_lines` in `process_program_proceedings` from 35 to 32 ([L388 in generate.py](https://github.com/rycolab/aclpub2/blob/main/aclpub2/generate.py#L388)), the median paper lines and max lines assumptions did not hold for us (IWSLT22)

**Comment by crux82** [comment]
@zhzhang can you please check this issue? This would avoid issues in the naacl workshop proceedings

**Comment by zhzhang** [comment]
got it! this is due to the table rendering overflowing due to a large number of multi-line entries. I'll adjust the tolerances.
